# Only used by ./test_gen.sh, see there for docs.

[versions]
image = "2025-06-05"
main_llvm = 19

[repo.fm-ci]

[repo.rocq-stdpp]
branch = "skylabs-master"
deps = ["fm-ci"]
vendored = true

[repo.BRiCk]
deps = ["fm-ci", "rocq-stdpp"]

[repo.skylabs-fm]
path = "."

[repo.auto]
deps = ["fm-ci", "BRiCk"]

[repo.nova-interface]
gitlab = "bluerock.nova-interface"
branch = "skylabs-main"
deps = ["fm-ci", "auto"]
path = "./bluerock/nova-interface"

[repo.NOVA]
gitlab = "bluerock.NOVA"
branch = "skylabs-proof"
deps = ["fm-ci", "nova-interface"]
path = "./bluerock/NOVA"
